services:
  laravel:
    image: bitnami/laravel:latest
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_DATABASE=laravel
      - MARIADB_USER=dokploy
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=root_password
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: